robot_num: 4
starts:
  - [4, 10]
  - [16, 10]
goals:
  - [16, 10]
  - [4, 10]
robot_radii:
  - 1.5
  - 1.5
  - 1.5
  - 1.5
width: 20
height: 20
lambda_factor: 0.5
expand_distances:
  - 3.0
  - 3.0
  - 3.0
  - 3.0
obstacles:
  - type: CircleObstacle
    x: 4
    y: 4
    radius: 4
  - type: CircleObstacle
    x: 10
    y: 6
    radius: 2
  - type: CircleObstacle
    x: 16
    y: 4
    radius: 4
  - type: CircleObstacle
    x: 4
    y: 16
    radius: 4
  - type: CircleObstacle
    x: 10
    y: 18
    radius: 2
  - type: CircleObstacle
    x: 16
    y: 16
    radius: 4
