startPoints:
  - [8, 8]
  - [2, 8]
  - [8, 2]
  - [2, 2]
goalPoints:
  - [2, 2]
  - [8, 2]
  - [2, 8]
  - [8, 8]
dimension: 2
spaceLimit:
  - 10.0
  - 10.0
robotRadii:
  - 1.0
  - 1.0
  - 1.0
  - 1.0
lambdaFactor: 0.5
maxExpandDistance: 3.0
neighborRadius: 3.0
maxIteration: 500
rectangleObstacles:
  - [5.0, 5.0, 4.0, 4.0]