robotNum: 3
startPoints:
  - [2.5, 2.5] # 파
  - [3.5, 2.5] # 초
  - [0.5, 0.5] # 보
goalPoints:
  - [4.5, 2.5] # 파
  - [1.5, 2.5] # 초
  - [0.5, 4.5] # 보
robotRadii:
  - 0.3
  - 0.3
  - 0.3
spaceLimits: [5.0, 5.0]
dimensions: 2
lambdaFactor: 0.5
neighborRadius: 5.0
maxIteration: 500
maxExpandDistance: 1.2
rectangleObstacles:
  - [2, 1, 2, 2]
  - [2.5, 3.5, 3, 1]