robot_num: 2
starts:
  - [4, 10]
  - [16, 10]
goals:
  - [16, 10]
  - [4, 10]
robot_radii:
  - 1.5
  - 1.5
width: 20
height: 20
lambda_factor: 0.5
expand_distances:
  - 1.2
  - 1.2
obstacles:
  - type: RectangleObstacle
    x: 10
    y: 4
    width: 20
    height: 8
  - type: RectangleObstacle
    x: 4
    y: 16
    width: 8
    height: 8
  - type: RectangleObstacle
    x: 10
    y: 18
    width: 4
    height: 4
  - type: RectangleObstacle
    x: 16
    y: 16
    width: 8
    height: 8
