robot_num: 5
starts:
  - [2.5, 2.5] # 파
  - [4.5, 2.5] # 초
  - [0.5, 3.5] # 빨
  - [1.5, 4.5] # 노
  - [0.5, 0.5] # 보
goals:
  - [4.5, 2.5] # 파
  - [1.5, 2.5] # 초
  - [2.5, 4.5] # 빨
  - [4.5, 0.5] # 노
  - [0.5, 4.5] # 보
robot_radii:
  - 0.3
  - 0.3
  - 0.3
  - 0.3
  - 0.3
width: 5
height: 5
lambda_factor: 0.5
neighbor_radius: 5.0
max_iter: 500
expand_distances:
  - 1.2
  - 1.2
  - 1.2
  - 1.2
  - 1.2
obstacles:
  - type: RectangleObstacle
    x: 2
    y: 1
    width: 2
    height: 2
  - type: RectangleObstacle
    x: 2.5
    y: 3.5
    width: 3
    height: 1