robot_num: 15
starts:
  - [2, 2]
  - [8, 8]
goals:
  - [2, 8]
  - [8, 2]
robot_radii:
  - 0.5
  - 0.5
  - 0.5
  - 0.5
  - 0.5
  - 0.5
  - 0.5
  - 0.5
  - 0.5
  - 0.5
  - 0.5
  - 0.5
  - 0.5
  - 0.5
  - 0.5
width: 30
height: 30
lambda_factor: 0.5
neighbor_radius: 5.0
max_iter: 500
expand_distances:
  - 5
  - 5
  - 5
  - 5
  - 5
  - 5
  - 5
  - 5
  - 5
  - 5
  - 5
  - 5
  - 5
  - 5
  - 5
obstacles: []