robot_num: 2
starts:
  - [2, 10]
  - [18, 10]
goals:
  - [18, 10]
  - [2, 10]
robot_radii:
  - 2.0
  - 2.0
width: 20
height: 20
lambda_factor: 0
collision_check_type: discrete
expand_distances:
  - 3
  - 3
obstacles: []
